(#11) Input Component
thebbodek/bbodek-ui pull request #49
Opened 2023-11-23 18:01 UTC by baegofda

(#11) Input Component

2023-11-24 02:28 UTC, Benj846 submitted a review, later dismissed

2023-11-24 05:29 UTC, cause38 submitted a review, later dismissed

2023-11-26 09:30 UTC, shinYeongHyeon requested changes

2023-11-26 09:30 UTC, shinYeongHyeon commented on src/core/components/Input/InputSearch/index.tsx
> +      <path d = "M17.9422 17.5577L14.0305 13.6468C15.1643 12.2856 15.7297 10.5398 15.609 8.77238C15.4883 7.00499 14.6909 5.35217 13.3827 4.15772C12.0744 2.96328 10.356 2.3192 8.58498 2.35944C6.81394
p1) @baegofda @cause38 @Benj846 
이런 아이콘들 따로 관리하는게 어떨까 합니다

2023-11-27 04:35 UTC, shinYeongHyeon submitted a review, later dismissed

2023-11-27 05:12 UTC, merged